### ISSUE TITLE
Library Loading Error (ValueError: object dtype is not supported by sparse matrices)

### ISSUE THREAD

**Issue by gerners** [bionetslab/digest#4]
Hi,
When trying to install digest, I ran into a few problems:

- cairo does not install via pip on Ubuntu, however via apt (sudo apt install libcairo2-dev) which made a following pip install without errors possible
- Cloning via "git clone git@github.com:digest-env/digest.git" lacks permissions/requires a key, however via  https it works fine. 

- After final install (Ubuntu 20.04.), both with and without conda, biodigest immediately fails with the following error message when loading the library:

gerners@LAPTOP-K7O8N2EJ:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import biodigest
Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/__init__.py", line 1, in <module>
		  from . import setup
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/setup.py", line 7, in <module>
		  from .evaluation.d_utils import runner_utils as ru, eval_utils as eu
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/__init__.py", line 1, in <module>
		  from . import comparator
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/comparator.py", line 3, in <module>
		  from .d_utils import eval_utils as eu
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/d_utils/__init__.py", line 2, in <module>
		  from . import plotting_utils
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/d_utils/plotting_utils.py", line 14, in <module>
		  from ..mappers.mapper import Mapper, FileMapper
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/mappers/__init__.py", line 1, in <module>
		  from . import disease_getter
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/mappers/disease_getter.py", line 7, in <module>
		  from .mapper import Mapper
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/mappers/mapper.py", line 14, in <module>
		  class Mapper:
	  File "/home/gerners/.local/lib/python3.8/site-packages/biodigest/evaluation/mappers/mapper.py", line 21, in Mapper
		  'jaccard': {'go_BP': sp.csr_matrix(None), 'go_CC': sp.csr_matrix(None), 'go_MF': sp.csr_matrix(None),
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 84, in __init__
		  self._set_self(self.__class__(
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 33, in __init__
		  arg1 = arg1.asformat(self.format)
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_base.py", line 376, in asformat
		  return convert_method(copy=copy)
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_coo.py", line 392, in tocsr
		  return self._csr_container(self.shape, dtype=self.dtype)
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 45, in __init__
		  self.data = np.zeros(0, getdtype(dtype, default=float))
	  File "/home/gerners/.local/lib/python3.8/site-packages/scipy/sparse/_sputils.py", line 113, in getdtype
		  raise ValueError(
ValueError: object dtype is not supported by sparse matrices
\>>>

Do you have an idea how to handle this error? I did not find anything useful when searching for this particular ValueError. Error happened on two different machines.

Best and thanks,
Samuel

**Comment by kadam0** [comment]
Dear Samuel,

thank you for the feedback and please excuse the long response time.

> * cairo does not install via pip on Ubuntu, however via apt (sudo apt install libcairo2-dev) which made a following pip install without errors possible
> 
Thank you for that hint, I will add it to the descriptions.

> * Cloning via "git clone [git@github.com](mailto:git@github.com):digest-env/digest.git" lacks permissions/requires a key, however via  https it works fine.
> 
This sounds like there is a ssh-key missing. Could you check, if you added your local ssh-key into github? If not, here is a guide on how to do it: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

> * After final install (Ubuntu 20.04.), both with and without conda, biodigest immediately fails with the following error message when loading the library:

On our machines, we couldn't recreate the error. But we a guess, what might have caused that and fixed that in the new version biodigest 0.2.5. Please test that and let us know if you still encounter that problem.

Best
Klaudia
